<<<<<<< HEAD
name: CI - API Inference
=======
name: CI Pipeline
>>>>>>> dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
<<<<<<< HEAD
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
=======
      - dev

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.10
>>>>>>> dev
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

<<<<<<< HEAD
      - name: 📦 Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Ejecutar pruebas
        run: |
          pytest --maxfail=5 --disable-warnings
=======
      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: ✅ Run Unit Tests
        run: make test
>>>>>>> dev
