name: CI - API Inference

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t api-inference-test .

      - name: Run Tests in Docker
        run: docker run --rm api-inference-test pytest tests/api/test_api.py
